#ifndef MESSAGE_PATCH
#define MESSAGE_PATCH

#include "global.h"
#include "z64horse.h"
#include "z64shrink_window.h"
#include "z64view.h"
#include "message_data_static.h"
// #include "interface/parameter_static/parameter_static.h"
#include "overlays/kaleido_scope/ovl_kaleido_scope/z_kaleido_scope.h"

u8 D_801C6A70 = 0;
s16 sOcarinaButtonIndexBufPos = 0;
s16 sOcarinaButtonIndexBufLen = 0;
s16 sLastPlayedSong = 0xFF;
s16 sOcarinaButtonStepR = 0;
s16 sOcarinaButtonStepG = 0;
s16 sOcarinaButtonStepB = 0;
s16 sOcarinaButtonFlashTimer = 12;
s16 sOcarinaButtonFlashColorIndex = 1;
s16 D_801C6A94 = 0;

s32 sCharTexSize;
s32 sCharTexScale;
s32 D_801F6B08;


u16 D_801D028C[] = {
    0x1B5A, // OCARINA_ACTION_0
    0x1B5B, //
    0x1B5C, // OCARINA_ACTION_DEMONSTRATE_SONATA
    0x1B5D, // OCARINA_ACTION_DEMONSTRATE_GORON_LULLABY
    0x1B5E, // OCARINA_ACTION_DEMONSTRATE_NEW_WAVE
    0x1B5F, // OCARINA_ACTION_DEMONSTRATE_ELEGY
    0x1B60, // OCARINA_ACTION_DEMONSTRATE_OATH
    0x1B61, // OCARINA_ACTION_DEMONSTRATE_SARIAS
    0x1B62, // OCARINA_ACTION_DEMONSTRATE_TIME
    0x1B63, // OCARINA_ACTION_DEMONSTRATE_HEALING
    0x1B64, // OCARINA_ACTION_DEMONSTRATE_EPONAS
    0x1B65, // OCARINA_ACTION_DEMONSTRATE_SOARING
    0x1B66, // OCARINA_ACTION_DEMONSTRATE_STORMS
    0x1B67, // OCARINA_ACTION_DEMONSTRATE_SUNS
    0x1B68, // OCARINA_ACTION_DEMONSTRATE_INVERTED_TIME
    0x1B69, // OCARINA_ACTION_DEMONSTRATE_DOUBLE_TIME
    0x1B6A, // OCARINA_ACTION_DEMONSTRATE_GORON_LULLABY_INTRO
    0,      // OCARINA_ACTION_11
    0xDC7,  // OCARINA_ACTION_3B
    0xDC9,  // OCARINA_ACTION_3C
    0x120A, // OCARINA_ACTION_DEMONSTRATE_EVAN_PART1_FIRST_HALF
    0x120B, // OCARINA_ACTION_DEMONSTRATE_EVAN_PART2_FIRST_HALF
    0x122C, // OCARINA_ACTION_DEMONSTRATE_EVAN_PART1_SECOND_HALF
    0x122F, // OCARINA_ACTION_DEMONSTRATE_EVAN_PART2_SECOND_HALF
    0x120A, // OCARINA_ACTION_PROMPT_EVAN_PART1_SECOND_HALF
    0x120B, // OCARINA_ACTION_PROMPT_EVAN_PART2_SECOND_HALF
};

s16 sOcarinaButtonAlphaValues[9] = { 0 };
u16 sOcarinaSongFlagsMap[] = { 1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800 };

void Message_FindMessage(PlayState* play, u16 textId);

#endif